
# Site
title: MDP.Net

# Theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Source Code on GitHub":
    - "//github.com/Clark159/MDP.Net"
color_scheme: dark
search_enabled: false

# Plugins
plugins:
  - jekyll-sitemap