
# Site
title: MDP.AspNetCore.Authentication

# Theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Source Code on GitHub":
    - "//github.com/Clark159/MDP.AspNetCore.Authentication"
color_scheme: dark
callouts:
  highlight:
    color: yellow
search_enabled: false
footer_content: "" 
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-sitemap